### ISSUE TITLE
[Question] Why do I need this mod client-side?

### ISSUE THREAD

**Issue by IntM4rco** [not-jun0/Create-Let-The-Adventure-Begin#1]
Hhy should I need this mod on client side, it just spawn structures like https://modrinth.com/datapack/create-structures which isn't needed on client-side.

**Comment by not-jun0** [comment]
i am not sure because i havnt tested it out yet but the mod also adds some blocks and items which makes it also client side. i think 
not sure

**Comment by not-jun0** [comment]
i just tested it and because of the blocks and items both the server and player needs to have it installed
