### ISSUE TITLE
[Bug] Structure in the ocean

### ISSUE THREAD

**Issue by IntM4rco** [not-jun0/Create-Let-The-Adventure-Begin#3]
https://mclo.gs/4gfrIHk

> ![2024-05-01_15 14 31](https://github.com/not-jun0/Create-Let-The-Adventure-Begin/assets/124934175/50605403-025c-4b09-a40f-a9d3563d5851)
> ![2024-05-01_15 14 37](https://github.com/not-jun0/Create-Let-The-Adventure-Begin/assets/124934175/27705826-7548-4195-9075-0c0b2432f68d)

**Comment by not-jun0** [comment]
its not a bug they are meant to spawn every where in the overworld

**Comment by IntM4rco** [comment]
Well, in my opinion it's bad enough to find a house in the ocean on a floating island.

**Comment by not-jun0** [comment]
Forgot to write it in here but i have now fixed the problem and hopefully it wont happen
